CREATE TABLE COMPLEX (
    COMPLEXNAME   CHAR(25) NOT NULL,
    COMPLEXABOUT  VARCHAR(2000),
    PUBNAME       VARCHAR(30),
    PUBDATE       VARCHAR(20),
    AUTHOR        VARCHAR(30),
    PRIMARY KEY ( COMPLEXNAME ),
    CONSTRAINT "Complex_Singleton" CHECK ( COMPLEXNAME IN 'The Smithsonian Institute' )
);

CREATE TABLE PROPERTY (
    PRNAME               VARCHAR(100) NOT NULL,
    PRDESCRIPTION        VARCHAR(1000),
    PROPERTYTYPE         VARCHAR(15),
    VISITINFO            VARCHAR(1000),
    PRLINK               VARCHAR(1000),
    PRSTREET             VARCHAR(15),
    PRCITY               VARCHAR(15),
    PRSTATE              VARCHAR(15),
    HIGHLIGHTS           VARCHAR(100),
    PRMAP                BFILE,
    FLOORPLAN            BFILE,
    TRANSPORTATION       VARCHAR(1000),
    PARKING              VARCHAR(100),
    ESTABLISHMENTNAME    VARCHAR(30),
    CURRENTRESTRICTIONS  VARCHAR(150),
    ACCESSIBILITY        VARCHAR(100),
    COMPLEXNAME          CHAR(25) NOT NULL,
    PRIMARY KEY ( PRNAME ),
    FOREIGN KEY ( COMPLEXNAME )
        REFERENCES COMPLEX ( COMPLEXNAME ),
    CONSTRAINT "Property_Complex_Singleton" CHECK ( COMPLEXNAME IN 'The Smithsonian Institute' ),
    CONSTRAINT "Property_Type_Values" CHECK ( PROPERTYTYPE IN ( 'Cultural Center', 'Research Center', 'Zoo', 'Garden', 'Gallery',
    'Museum' ) )
);

CREATE TABLE "COLLECTION OBJECT" (
    OBJECTRECORDID     INTEGER NOT NULL,
    OBJECTNAME         VARCHAR(30),
    OBJECTTYPE         VARCHAR(30),
    OBJECTDESCRIPTION  VARCHAR(1000),
    OBJECTKEYWORDS     VARCHAR(1000),
    PRNAME             VARCHAR(100) NOT NULL,
    PRIMARY KEY ( OBJECTRECORDID ),
    FOREIGN KEY ( PRNAME )
        REFERENCES PROPERTY ( PRNAME ),
    CONSTRAINT "Object_Type_Values" CHECK ( OBJECTTYPE IN ( 'cultural artifact', 'scientific artifact', 'historical artifact', 'animal',
    'plant' ) )
);

CREATE TABLE PERSON (
    FIRSTNAME         VARCHAR(15) NOT NULL,
    LASTNAME          VARCHAR(30) NOT NULL,
    PERSTREET         VARCHAR(15) NOT NULL,
    PERCITY           VARCHAR(15),
    PERSTATE          VARCHAR(30),
    PERPOSTALCODE     CHAR(5),
    EMAILADDRESS      VARCHAR(50),
    CREDITCARDNUMBER  CHAR(16),
    EXPIRATION        VARCHAR(15),
    SECCODE           CHAR(3),
    PRIMARY KEY ( FIRSTNAME,
                  LASTNAME,
                  PERSTREET )
);

CREATE TABLE VISIT (
    FIRSTNAME  VARCHAR(15) NOT NULL,
    LASTNAME   VARCHAR(30) NOT NULL,
    PERSTREET  VARCHAR(15) NOT NULL,
    PRNAME     VARCHAR(100) NOT NULL,
    PRIMARY KEY ( FIRSTNAME,
                  LASTNAME,
                  PERSTREET,
                  PRNAME ),
    FOREIGN KEY ( FIRSTNAME,
                  LASTNAME,
                  PERSTREET )
        REFERENCES PERSON ( FIRSTNAME,
                            LASTNAME,
                            PERSTREET ),
    FOREIGN KEY ( PRNAME )
        REFERENCES PROPERTY ( PRNAME )
);

CREATE TABLE "MEMBER" (
    MEMBERNUMBER  INTEGER NOT NULL,
    MEMBERLEVEL   VARCHAR(30),
    COMPLEXNAME   CHAR(25) NOT NULL,
    PRIMARY KEY ( MEMBERNUMBER ),
    FOREIGN KEY ( COMPLEXNAME )
        REFERENCES COMPLEX ( COMPLEXNAME ),
    CONSTRAINT "Member_Complex_Singleton" CHECK ( COMPLEXNAME IN 'The Smithsonian Institute' )
);

CREATE TABLE DONATION (
    MEMBERNUMBER   INTEGER NOT NULL,
    COMPLEXNAME    CHAR(25) NOT NULL,
    AMOUNTDONATED  REAL,
    PRIMARY KEY ( MEMBERNUMBER,
                  COMPLEXNAME ),
    FOREIGN KEY ( MEMBERNUMBER )
        REFERENCES "MEMBER" ( MEMBERNUMBER ),
    FOREIGN KEY ( COMPLEXNAME )
        REFERENCES COMPLEX ( COMPLEXNAME ),
    CONSTRAINT "Donation_Complex_Singleton" CHECK ( COMPLEXNAME IN 'The Smithsonian Institute' )
);

CREATE TABLE EVENT (
    EVNUMBER       INTEGER NOT NULL,
    EVNAME         VARCHAR(20),
    EVDATE         VARCHAR(20),
    LOCATION       VARCHAR(30),
    ADMISSIONCOST  REAL,
    COSPONSOR      VARCHAR(20),
    VENUE          VARCHAR(30),
    EVDETAILS      VARCHAR(1000),
    NOTE           VARCHAR(150),
    EVLINK         VARCHAR(1000),
    PRNAME         VARCHAR(100) NOT NULL,
    PRIMARY KEY ( EVNUMBER ),
    FOREIGN KEY ( PRNAME )
        REFERENCES PROPERTY ( PRNAME ),
    CONSTRAINT "Event_Venue_Date" UNIQUE ( EVDATE,
                                           VENUE )
);

CREATE TABLE EXHIBITION (
    EXNUMBER       INTEGER NOT NULL,
    EXDESCRIPTION  VARCHAR(1000),
    EVNUMBER       INTEGER NOT NULL,
    PRIMARY KEY ( EXNUMBER ),
    FOREIGN KEY ( EVNUMBER )
        REFERENCES EVENT ( EVNUMBER )
);

CREATE TABLE DISPLAYS (
    OBJECTRECORDID  INTEGER NOT NULL,
    EXNUMBER        INTEGER NOT NULL,
    PRIMARY KEY ( OBJECTRECORDID,
                  EXNUMBER ),
    FOREIGN KEY ( OBJECTRECORDID )
        REFERENCES "COLLECTION OBJECT" ( OBJECTRECORDID ),
    FOREIGN KEY ( EXNUMBER )
        REFERENCES EXHIBITION ( EXNUMBER )
);

CREATE TABLE "EDUCATION INITIATIVE" (
    EDNAME         VARCHAR(100) NOT NULL,
    EDDESCRIPTION  VARCHAR(1000),
    PRNAME         VARCHAR(100) NOT NULL,
    PRIMARY KEY ( EDNAME ),
    FOREIGN KEY ( PRNAME )
        REFERENCES PROPERTY ( PRNAME )
);